### ISSUE TITLE
OAG dataset administration

### ISSUE THREAD

**Issue by richard-jones** [CottageLabs/LanternPM#10]
OAG relies on a per-publisher and generic list of article statements and their mappings to known open licences.  This dataset needs to be constantly checked, maintained, and extended to cover as many publishers as possible.

We need to put into place an administrative (human) process to look after this dataset, and to gather requirements on improving the data management interface.

We have an administrator who is willing to take this on, so I just need to document the task and go through it with them.

**Comment by richard-jones** [comment]
This issue has now changed focus:

@emanuil-tolev will do the following:
1. Make a google spreadsheet to be the source of all licences
2. Extract specific licence texts from OAG index
3. Extract licence texts from licence.py
4. Extract licences from the standard CC licence variations in Lantern
5. [optionally] Check OAG backups for licence statements

**Comment by emanuil-tolev** [comment]
https://docs.google.com/spreadsheets/d/1yJOpE_YMdDxCKaK0DqWoCJDdq8Ep1b-_J1xYVKGsiYI/edit#gid=0 . Steps 1-3 done.

**Comment by richard-jones** [comment]
There is a spreadsheet now for managing licences, so this issue is obsolete
