### ISSUE TITLE
Bug in UI for account allowance

### ISSUE THREAD

**Issue by richard-jones** [CottageLabs/LanternPM#107]
One of our test users is seeing this on their home page:

```
You can submit up to 5000 IDs in a 30 day period.
You have submitted 9757 IDs in the last 30 days.
You can submit up to 45243 more IDs now.
```

The account has an additional 50,000 IDs per month applied through the admin UI, so I'd expect the first line to reflect that.

(also, can we format the numbers a bit better for humans, with comma separators?)

**Comment by markmacgillivray** [comment]
Should be fixed. @richard-jones please check with this user or tell me who they are so I can try looking, then close this issue.

**Comment by markmacgillivray** [comment]
No longer relevant
