### ISSUE TITLE
EPMC licence unknown, even though licence in HTML

### ISSUE THREAD

**Issue by richard-jones** [CottageLabs/LanternPM#113]
http://europepmc.org/articles/PMC4142863 came up as epmc licence unknown, when the licence is clearly in the html, and this article: http://europepmc.org/articles/PMC4142975

seems to have its licence in the html in exactly the same way, and the epmc licence has been identified correctly as cc by

@emanuil-tolev to review and pass to @markmacgillivray if work required

**Comment by emanuil-tolev** [comment]
I wonder if this is intermittent as well. They are being detected correctly via the EPMC HTML now.

**Comment by markmacgillivray** [comment]
Finds as expected. Only remaining issue is highly likely that we were blocked on the UI. Closing this issue.
