### ISSUE TITLE
Progress update failing to update % until refresh 

### ISSUE THREAD

**Issue by emanuil-tolev** [CottageLabs/LanternPM#116]
Got a report (wellcome UI):

> it sent me the email to say it was all done, but then when I went to the page it said it was only 72.4% complete, until I refreshed it – then it said it was 100% complete.

**Comment by emanuil-tolev** [comment]
Note, this is on IE11.

**Comment by markmacgillivray** [comment]
Probably nothing we can do about that. The polling does work, and if they
are seeing any poll count at all it must be working for them, but at any
point a user could lose connection for a multitude of reasons. If it is a
long running job, the polling could fail at some point and yes they would
have to refresh. We could force a page refresh on poll fail, but then some
browsers will consider a page refresh to be a bad behaviour that they will
warn the user for.

**Comment by emanuil-tolev** [comment]
You know, gmail and Trello (to take 2) display a bit of text just saying the page you're looking at is out of date, and that you should refresh. This would solve the problem, since the actual problem is not so much one of robust progress polling, but user confusion where the user believes the page is up to date, but it actually isn't. Could we do that relatively simply in the AJAX fail handler?

**Comment by markmacgillivray** [comment]
Probably.

**Comment by richard-jones** [comment]
Take into account in new site design

**Comment by richard-jones** [comment]
after a bit of discussion, we think this is hard/impossible to solve, so closing off unless it becomes an issue again
