### ISSUE TITLE
Lantern documentation review

### ISSUE THREAD

**Issue by emanuil-tolev** [CottageLabs/LanternPM#117]
There have been changes and bugfixes to the Wellcome project, some of which of course affect how Lantern behaves. Review https://lantern.cottagelabs.com/docs versus https://compliance.cottagelabs.com/docs and update the former if necessary.

I am happy to do this myself, as I just completed a Wellcome docs review #105 .

**Comment by richard-jones** [comment]
Documentation review is being done as part of new site design, so closing
