### ISSUE TITLE
Configurable output

### ISSUE THREAD

**Issue by richard-jones** [CottageLabs/LanternPM#127]
In order to provide different types of user with a customised view, the system should offer the following:

* A set of options on the user's account page which allows them to select which columns to include/exclude from their download of results.  This should include all the factual columns as well as the two Wellcome compliance calculations

* On the job download page, the user should be able to see the options, and they are pre-set to the options specified on the account page.  The user should be able to override them for that particular download (i.e. changing them here doesn't affect their default account settings).

* UI documentation (in-line basic documentation, with an option to see the full docs either by link to the docs page or in an expanding section) in both places explaining the options.

**Comment by richard-jones** [comment]
Worth noting that I don't think that this functionality affects at all how jobs are run, only how they are downloaded

**Comment by markmacgillivray** [comment]
@richard-jones I have not made improvements to the UI layout yet so it does not look great, but an implementation of the above is now in place on the lantern.test site. Please have a look, and let me know if that looks functionally complete.

Regarding the UI docs, am I doing that or are you? If me, what do you mean by UI docs? Is this just a link through to the normal docs, or something specific about selecting their download fields that you want to be explained somehow?

I think based on your email earlier this week that this is what is needed in Jan for Wellcome move, so if you can review and let me know soon if it works as expected, I can make some UI improvements before the 16th too.

**Comment by richard-jones** [comment]
I'm logged into Lantern but I'm not sure how to see the settings - is there a specific page that I need to go to?

**Comment by richard-jones** [comment]
For the UI docs, I am happy to do them, or at least provide the text.  I was thinking that by each checkbox we'd need to be clear which fields in the resulting output would be affected, and that would be easier to do inline rather than by a link to the main docs.  So probably a short description inline so users can quickly understand, and a link to the main docs for full details about the nature of the fields.

**Comment by markmacgillivray** [comment]
If you're on the lantern test site and logged in you should just see them at the bottom of the page. Below your list of jobs. Then when you look at a job page you should see them there too, for one-time changes.

**Comment by richard-jones** [comment]
Ah, got it, sorry I was on the live site!

Yes, functionally seems to be working fine.  I didn't see a save button on the checkboxes, I presume they just save automatically when you change them?

For the UI we need to make it as clear as possible that there's an "account" setting, which will always be applied, and and override which can be applied on a per download basis which doesn't affect your default settings.  Not sure what the best way to do this is, but probably need to put the options up near the download button, perhaps in a collapsible section?

Looking at it, I'm also not sure about the docs now.  Initially I think we'll just link to the documentation, but in the long run I'm thinking that it might be better to have the field documentation in a database, so that we can surface it in-context, e.g. in tool tips, around the site.  What do you think?

**Comment by richard-jones** [comment]
We will need this functionality for the Organisation Account, though exactly how it is surfaced/used has yet to be determined.
