### ISSUE TITLE
"Unauthorised" when submitting from a non-admin, non-premium account

### ISSUE THREAD

**Issue by emanuil-tolev** [CottageLabs/LanternPM#134]
Account: emanuil.tolev@gmail.com
File (though I don't think it matters what file you submit): [mitochondrion_lantern.csv.zip](https://github.com/CottageLabs/LanternPM/files/789968/mitochondrion_lantern.csv.zip)

![image](https://cloud.githubusercontent.com/assets/1190172/23163437/59048d78-f82a-11e6-87e9-f8b736e3412c.png)

**Comment by markmacgillivray** [comment]
Fixed

**Comment by emanuil-tolev** [comment]
Wow, that was fast :). Thanks!
