### ISSUE TITLE
Disable EPMC UI lookups for non-Wellcome users

### ISSUE THREAD

**Issue by richard-jones** [CottageLabs/LanternPM#137]
Due to the ongoing issues with scraping from the EPMC UI, we should disable the lookup there for non-Wellcome user accounts.  We may need to review the spreadsheet output and make sure that it is clear to the end user that there is a source of data that we have not looked at.  Perhaps just by putting a note in the provenance?  So, in the case where we would usually have looked up something in the UI, we instead put a note in saying which bit of information we're still missing, and where they can look for it manually (i.e. provide them with the URL to the page we would have originally scraped).

**Comment by richard-jones** [comment]
Also, raise the rate limit for EPMC UI for Wellcome to 10s

**Comment by markmacgillivray** [comment]
Disabled, and configurable via system config. Limit was already raised to 10s.
