### ISSUE TITLE
Implement back-end of credit system

### ISSUE THREAD

**Issue by richard-jones** [CottageLabs/LanternPM#145]
payments (see #141 ) should result in the user account being given a requisite number of credits.  Payment to credit amount should be configurable, so we can change it in the future.  We should also always keep track of the actual financial transactions the user made in case we need to audit or correct for bugs later.

It should be possible to add credit to a user's account without payment, but only by us.

One credit should be used per identifier included in a bulk run.  Do not incur credit costs for individual identifier runs.  We should keep track of number of credits used and when, in case we need to audit or correct for bugs later.

**Comment by markmacgillivray** [comment]
Unnecessary at present
