### ISSUE TITLE
Ability to log in/out on machine with no email access

### ISSUE THREAD

**Issue by richard-jones** [CottageLabs/LanternPM#22]
For presentations and the like, would be good to be able to log in/out of a machine where there is no email access or the time to wait for the email is unavailable.

**Comment by markmacgillivray** [comment]
I mentioned I noticed a time where mailgun took three hours to send me login emails, which was the first time I actually saw evidence of it taking longer than a minute (although we did know it was slower than mandrill). Mailgun responded saying that coincided with a one-time issue on their servers where they built up a backlog and that it was not a specific problem with our attempts, and that they had solved the problem. BUT - if we have anecdotal evidence of emails taking a few hours, we still have a problem. For now, mailgun will do. I will implement a way for someone who has already signed up to sign in quicker - but first sign in still carries a risk of delay. The only way round this would be to actually let people use the system before we have validated them at all, but this would leave us more easily open to spamming and ddosing...

**Comment by markmacgillivray** [comment]
I have implemented device registration, so that with a registered device it is possible to read the logincodes there. For the time being this works for presentations etc, and we could extend the functionality for other login use cases.
