### ISSUE TITLE
Premium account website copy

### ISSUE THREAD

**Issue by richard-jones** [CottageLabs/LanternPM#23]
Add information about premium account benefits, and the process of getting a premium account.  Also, update the terms with any associated information.

**Comment by markmacgillivray** [comment]
Where are you at with this one? Want me to add a button next to this new content you're adding, before OR? If so let me know once you have pushed the content and I will add a button. Or you can just add a standard mailto button to the page content you add. Let me know either way, so I can complete / close #24

**Comment by richard-jones** [comment]
I've added the first version text to the front page, and updated the terms to match.  I've pushed to master, but it doesn't seem to have deployed yet - maybe the CI is off at the moment, while you're making the bigger changes?

Right now there is just a mailto button which emails to lantern@cottagelabs.com, so if you could make that address exist and have it forward to the 3 of us that would be great.

If you wanted to make the button smarter, though, and have it just email us with the user's account details and a short message for context, and then show the user a "thank you" pop up, that would also work.

**Comment by richard-jones** [comment]
Also, when you implement Premium Accounts on the user's account, can you make it so that these bits of text disappear for premium users?

**Comment by markmacgillivray** [comment]
This is done. When a user submits a job that takes them over their quota, the job is refused and they are told it is too big for their quota allowance. UI is being updated now to show their current allowance so they could manually edit the job to be an acceptable size. This could be changed to accept PART of the job, but I am not sure that is a better approach, as it takes the thought process away from the user so they may be more confused by the end result. So for now, this is the way it is. But could change later if desired.

**Comment by richard-jones** [comment]
I'm seeing the following now on the Lantern page:

"""
You can submit up to 100000 IDs in a 30 day period.

You have submitted 100000 IDs in the last 30 days.

You can submit up to 100000 more IDs now.
"""

One of those statements must be wrong.

How do I log out so that I can see the unauthenticated, and/or non-premium
pages?  Can you give me a non-premium account that I can log into for
testing?

Cheers,

Richard

## 

Richard Jones,

Founder, Cottage Labs
t: @richard_d_jones, @cottagelabs
w: http://cottagelabs.com

**Comment by markmacgillivray** [comment]
I suspect you are stuck in limbo. The 100000 count is only for when there is no account present (a large number to allow wellcome processing). You have an account on the dev system but not on the live system, but you probably previously logged into the lantern UI when it was attached to the dev API. Go to test.cottagelabs.com and click the logout button if you can see it. Also go to accounts.cottagelabs.com and I expect you would not be logged in anyway. Then go to lantern.cottagelabs.com and you should be logged out. Then login again - this will create your account on the live system. You should then find you have a limit of 100, because there are no premium accounts yet! I am working on the UI to add premium and admin accounts now.

**Comment by markmacgillivray** [comment]
Oh also those statements that you see should make sense now - I was in the process of updating the live API right when you must have made that request.

**Comment by richard-jones** [comment]
Ah, ok.

Could you also put the link to the docs and terms on the unauthenticated
page?

Cheers,

Richard

On 13 June 2016 at 11:11, markmacgillivray notifications@github.com wrote:

> Oh also those statements that you see should make sense now - I was in the
> process of updating the live API right when you must have made that request.
> 
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> https://github.com/CottageLabs/LanternPM/issues/23#issuecomment-225541266,
> or mute the thread
> https://github.com/notifications/unsubscribe/AA0QSpZmy1x1_3tuwH0M1qxShCId_A21ks5qLSzmgaJpZM4InwSY
> .

## 

Richard Jones,

Founder, Cottage Labs
t: @richard_d_jones, @cottagelabs
w: http://cottagelabs.com

**Comment by markmacgillivray** [comment]
OK I can see you have an account on the live system now, and I have added the docs and terms links to the unauthenticated page. Continuing with the UI for adding premium and admin users now. I will leave this ticket open in case you have any more issues, close it if you are happy.

**Comment by markmacgillivray** [comment]
Account quotas are now in place. UI for controlling premium is also ready, will email about that.
