### ISSUE TITLE
Server error on retrieving job

### ISSUE THREAD

**Issue by richard-jones** [CottageLabs/LanternPM#26]
This job was uploaded yesterday, but on attempting to retrieve it this morning, the "download results" link resulted in a server error

https://lantern.cottagelabs.com/#LcSoNqZtBK9aD5aPF

**Comment by richard-jones** [comment]
For a CSV with 2500 records ...

 the ‘Download your results’ link just gives a server error. I’ve tried uploading 1000 DOIs, but this produces the same result. Another job of 500 DOIs doesn’t complete, however you can download the partial results (https://lantern.cottagelabs.com/#2ADhQGLEyePq9ezGK). A file with 100 DOIs runs to completion, and all the results can be downloaded (https://lantern.cottagelabs.com/#Wu8xWdF9dbvSrZjmK).

**Comment by markmacgillivray** [comment]
This is in the wellcome milestone - should it be in lantern?

**Comment by markmacgillivray** [comment]
Ah it seems wellcome means wellcome/lantern in some cases, I guess.

**Comment by markmacgillivray** [comment]
A tolowercase error on grant agency data I previously fixed but forgot to add to the lantern formatting. Fixed now, pushing to live.
