### ISSUE TITLE
Stop using the EPMC Rest API for licence information

### ISSUE THREAD

**Issue by richard-jones** [CottageLabs/LanternPM#29]
Currently this is affecting the app badly in 3 ways:
- the non-normalised representation of licences. Cecy and friends would like data in the licence column to be normalised (so CC BY is only ever represented as "cc-by", not "cc by").
- the Compliance columns: right now they say FALSE for every epmc_rest_api result because I assume the compliance algorithm is looking for a "cc-by" licence type specifically.
- some data is just weird, like 7 articles with just "cc" in the licence which is ambiguous. That's no use and we would have gotten better information if we scraped the EPMC HTML page for the article - the licence is actually CC BY.

**Comment by emanuil-tolev** [comment]
Resolved in May.
