### ISSUE TITLE
Author manuscript metadata is wrong in EPMC

### ISSUE THREAD

**Issue by richard-jones** [CottageLabs/LanternPM#31]
Basically the EPMC XML field we are using (<epmcAuthMan>Y</epmcAuthMan>) is sometimes wrong. Instead we should use page scraping of the EPMC HTML page as the only way to detect AAM status. We already do some string scraping, but see https://docs.google.com/document/d/1Y86YwBIpQ2gM7bX_GjNKSM8-SWayVU_iOcF_mNrCfrg/edit , search "Upon further testing of the author manuscript column" to get the exact HTML

**Comment by emanuil-tolev** [comment]
Resolved on 27 May, see linked PR above this comment.
