### ISSUE TITLE
Separate licences from different sources into different columns

### ISSUE THREAD

**Issue by richard-jones** [CottageLabs/LanternPM#33]
This is a requirement that has arisen recently with Wellcome, but it's not clear yet what the broader impact of this is in terms of general Lantern development.

Propose that this is /not/ tacked immediately, instead we review what the consequences of going this way would be, and consider it as a feature for the future.

**Comment by markmacgillivray** [comment]
Is Emanuil aware of this issue and the proposal not to tackle it yet? As I
understand from earlier messages, he is already proceeding with doing so.

Mark

**Comment by emanuil-tolev** [comment]
I think Richard means supporting it for Lantern users, and thinking if it would be useful for them? (Well, rather, not thinking about offering it to Lantern users at all for now, only Wellcome.)

**Comment by richard-jones** [comment]
Actually, I mean in general not support this for the next version for Wellcome.  It is a new requirement, so I don't think it's an issue to suggest that it comes later, if at all.

I don't feel that we've thought this feature through, so I'm hesitant to recommend doing it straight away.  For example, does this mean that there should be a column for every possible source for the licence?  And does it mean, therefore, that we should look the licence up in all sources, even if we've already got it from one place?

**Comment by markmacgillivray** [comment]
Perhaps, just wanting to make sure it is clear, hence checking.

Mark

**Comment by emanuil-tolev** [comment]
> I don't feel that we've thought this feature through, so I'm hesitant to recommend doing it straight away. For example, does this mean that there should be a column for every possible source for the licence? And does it mean, therefore, that we should look the licence up in all sources, even if we've already got it from one place?

No, to both.

There's a Publisher Licence column. Then there are the EPMC Licence and EPMC Licence Source columns. There's no point in a Publisher Licence Source column. As in, if it's a publisher licence then obviously it came from the publisher's website. If we didn't manage to find a licence on the publisher's website then it's "unknown".

The only change to licence algorithm is to now look up a licence on the publisher site if the one from EPMC is not "cc-by" or "cc-zero". So if the EPMC licence is unknown, or non-standard, we try the publisher's site. As opposed to now, when we only try the publisher's site if the EPMC licence is unknown. The only new thing is actually "run publisher licence check if EPMC has a non-compliant licence".

This seems clear enough. It's also a small change to the logic (and bigger change to Wellcome's output format) which would be useful to Lantern as well as Wellcome users, and it does not result in loads of extra processing - articles marked CC-BY or CC0 in EPMC will still not be run through the publisher licence checker.

**Comment by emanuil-tolev** [comment]
As a different recap... we're doing two things:
- We already fetch all this information, but rather than overwriting it in one Licence column we're simply unpacking it into 2 columns. Exact same values as we pack into 1 column now, same logic.
- Running the publisher licence check if the EPMC licence is not CC-BY or CC0, as opposed to only running it when the EPMC licence is unknown.

**Comment by richard-jones** [comment]
Ok, if you're happy that this is easy and makes sense to the user for Wellcome, that's fine with me.

I'm just keeping my eye on the future, where we might get licence information from more sources (e.g. CrossRef licence_ref, directly from a repository, etc), and how the idiom plays out in those contexts.  Once we start breaking out the columns, we might need to go all the way ...

**Comment by emanuil-tolev** [comment]
@markmacgillivray I'm pretty much done with this, except for 1 difficulty I'm having with output formatting, around the substitution list `s` in the formatting function, and how it interacts with what I want to do (output "not applicable" in Publisher Licence if Publisher Licence Source is one of the EPMC ones). I'll add it to PR #1 early tomorrow. That pr can be critiqued or merged regardless though, I'll just open a new one for this feature.

**Comment by emanuil-tolev** [comment]
This is done and works well, not affecting Lantern output, but being output correctly in Wellcome format.
