### ISSUE TITLE
make upload error message to user more user-friendly

### ISSUE THREAD

**Issue by richard-jones** [CottageLabs/LanternPM#38]
If the user experiences an upload error, they see something like

Sorry, there has been an error with your submission. Please try again.
If you continue go receive an error, please contact us@cottagelabs.com with the following error information:
{"readyState":0,"responseText":"","status":0,"statusText":"error"}”

The status information doesn't seem to say very much, and it will probably be confusing to users.  Is there a way that we can give them something easier to look at, or more informative?  For example, in previous systems we've given the users a magic number (a uuid) which has been logged at our end, so we can track their request through the logs to debug it.

**Comment by richard-jones** [comment]
It would be good if we can distinguish between the kinds of errors the users might see:
- Spreadsheet is too large
- Can't read your sheet because it's corrupt
- Can't read your sheet because it's the wrong shape
- Some kind of communication error with the back-end

Maybe others?

**Comment by emanuil-tolev** [comment]
- Please use a .csv if the file is not a .csv (e.g. if it's .xlsx). Right now on upload of .xlsx shows:
  ![image](https://cloud.githubusercontent.com/assets/1190172/16984548/90191548-4e72-11e6-86f2-2f714538d31f.png)

**Comment by richard-jones** [comment]
Another error condition:
- you have exceeded your quota

Also, contact email should be lantern@cottagelabs.com

**Comment by richard-jones** [comment]
The quota mentioned above is no longer relevant, but:

* You don't have sufficient credit
* malformed input string (not comma separated)
* uploaded a file that's not a csv (e.g. an xls)
