### ISSUE TITLE
Account/login user workflow

### ISSUE THREAD

**Issue by richard-jones** [CottageLabs/LanternPM#40]
From a user:
- At the moment it’s a bit frustrating because the ‘single use login’ email takes quite a while to appear in our inbox
- The link works and takes me to our ‘account’ screen, and there doesn’t appears to be an easy way to get to file upload bit
- But If I then go to the main latern URL I appear to be logged in successfully and can upload a file.
- There doesn’t appear to be an easy way to navigate to the current job status. If I close the page and follow the link on the email it takes me to the account page, not the current job status.

**Comment by markmacgillivray** [comment]
TODO, for my own thoughts:
1. still not sure about best solution, multiple options
2. should redirect but clearly sometimes does not, change default to a list of links to services so user can choose if not redirected
3. As expected
4. Can improve on 3 to provide a list of current user jobs. Apart from that, this sounds very much like just an error in use - the link followed must have been the login link, not the job link.

**Comment by markmacgillivray** [comment]
All done except 1 (but none pushed to live yet).

**Comment by markmacgillivray** [comment]
Will close this one now, as #22 covers the remaining issue.
