### ISSUE TITLE
Compliance algorithm appears incorrect - add new cc0 name

### ISSUE THREAD

**Issue by emanuil-tolev** [CottageLabs/LanternPM#45]
Actually, it probably is correct, but the non-normalised EPMC Rest API licence info is throwing it off. This bit will be resolved when we stop using the API.

Additionally, we must add a condition: an article is compliant if the licence type is "cc-zero" as well. I think the old tool used "cc0" internally and our new licence sheet detects "cc-zero" instead, so we need to make "cc-zero" compliant as well.

**Comment by richard-jones** [comment]
In my dev version of the licence sheet, I have reverted that to cc0.  Was there a reason we started using cc-zero instead?

**Comment by emanuil-tolev** [comment]
> In my dev version of the licence sheet, I have reverted that to cc0. Was there a reason we started using cc-zero instead?

The compliance algo now accepts both cc0 and cc-zero as part of the fix for this.

OAG used cc-zero internally to denote this licence. OACWellcome used cc0.

**Comment by emanuil-tolev** [comment]
Cecy did notice that, and I suppose cc0 would be nice as it would be the same as old Lantern/old OACWellcome used to return, so feel free to update it - all that's needed is the licence sheet change you've made.

**Comment by emanuil-tolev** [comment]
> In my dev version of the licence sheet, I have reverted that to cc0. Was there a reason we started using cc-zero instead?

@richard-jones I have made changes to the live licence sheet as part of doing all the Wellcome work last week, so careful to merge them in - if you give me a link to your version of the sheet I can ensure the new records are recorded in there, since I know what changes I made. I'm afraid there are some changes across many rows rather than just a few additions - like free-to-read being consolidated to non-standard-licence.

**Comment by emanuil-tolev** [comment]
Leaving open since it appears that I misunderstood Wellcome's brief here, or it was unclear - basically an article is only compliant if the licence in EPMC is cc-by or cc-zero or cc0. If the _publisher_ licence is one of these, they will see that in the Publisher Licence column, but it should not play a role in compliance calculation.

**Comment by emanuil-tolev** [comment]
Resolved. #54 took care of this.
