### ISSUE TITLE
UI issues

### ISSUE THREAD

**Issue by emanuil-tolev** [CottageLabs/LanternPM#47]
From Wellcome feedback, here are the UI issues not already described in other issues in this tracker:

2. Could you put the name of the spreadsheet on the processing page? This helps to identify what is being processed when processing multiple spreadsheets. (And for the same reason it’s great that you’ve put the file name in the subject line of the email - much easier!).

3. Similarly the file name of the processed spreadsheet should contain the original file name. I suggest you use the same format as is currently used by the live site. E.g., “spreadsheet_1” becomes “Processed_spreadsheet_1”.
    ET: It does, it’s currently “spreadsheet_1_results.csv”...
    ET: Aaah! But only if your original sheet has no spaces in the filename… we need to make it work for spaces in the filename too. If you upload "Compliance - analysis_Aug 2015_PubMed.csv" the results file will just be called "Compliance" - no extension or `_results` suffix. 

6. The browser tab should be changed to something like “OA compliance tool”.

**Comment by markmacgillivray** [comment]
1. Done, 3. Done, replaces whitespace with _ in case that was causing an issue, 6. Done (has to be done via js)
