### ISSUE TITLE
Mailshots to account holders

### ISSUE THREAD

**Issue by richard-jones** [CottageLabs/LanternPM#49]
Soon I'm going to need to be able to do mailshots to account holder (e.g. when terms and conditions change), so it would be useful to have an easy way to either do that through the system, or get the email addresses of current account holders out, perhaps as a csv so I can feed it into some mailing software.

**Comment by markmacgillivray** [comment]
Both are possible. I have started this sort of group UI work as part of oabutton, I will create similar for lantern asap, but after OR

**Comment by richard-jones** [comment]
removing from issue tracker, we will develop a process for mailshots at a future date
