### ISSUE TITLE
Provided identifiers being overwritten

### ISSUE THREAD

**Issue by emanuil-tolev** [CottageLabs/LanternPM#50]
The sheet

```
PMID
9
```

gets overwritten with

```
PMID,DOI
27143954,10.2147/mder.s108982
```

Why? This article is not the article represented by PMID 9.

**Comment by markmacgillivray** [comment]
Added some extra config to europepmc user that should have been there in the first place, and a try / catch around the text extract in academic/licence - sometimes the source may not be extractable in a useful way, so just does not run if there is no use in running it. Checked the query and it now properly finds the article associated to this PMID. Assuming this solves the problem now.
