### ISSUE TITLE
Cookie warning on main site

### ISSUE THREAD

**Issue by richard-jones** [CottageLabs/LanternPM#64]
Just trying to determine whether we need to comply with this law:

https://ico.org.uk/for-organisations/guide-to-pecr/cookies-and-similar-technologies/

I believe we are exempt because the cookies are required to provide an on-request service, but just attempting to confirm.

**Comment by markmacgillivray** [comment]
This is not required. At the time a big deal was made about how they were compulsory by law. But shortly after, that was rescinded. One of those cases where people said "EU making us do stupid stuff" when actually they did not.

**Comment by markmacgillivray** [comment]
Or as you say, it is not required in our case because it is functional the act of logging in. The big noise was that people thought it was necessary no matter what, but that was clarified, as described on the page you linked to.

**Comment by markmacgillivray** [comment]
And also since the law was introduced it has been ignored, even by the ICO themselves.

https://silktide.com/the-stupid-cookie-law-is-dead-at-last/

**Comment by richard-jones** [comment]
Sounds good enough to me.
