### ISSUE TITLE
Final changes to Wellcome UI and documentation

### ISSUE THREAD

**Issue by emanuil-tolev** [CottageLabs/LanternPM#65]
These can probably be done in parallel to deploying the service live (they're all cosmetic changes or docs changes - which we might need to do after the first live deployment anyway).
- [x] Not very important - styling issue on Firefox (confirmed with newest one, but this pic is 44.0.2)
  
  Text input would ideally be a tad taller so as to not cut off the "Browse" button. I've no idea why this is an issue - presumably bootstrap should have taken care of this, so there must be either an override or simply an unintended clash of styles.
  
  ![image](https://cloud.githubusercontent.com/assets/1190172/16389154/79216a2e-3c94-11e6-98d4-1aafb770643a.png)
- [x] Documentation page title should also say “Wellcome compliance tool” not “Cottage Labs”
- [x] Various docs page text changes listed on page 11 and 12 of the Wellcome feedback doc (not pasting link since it's edit-by-link sharing).

**Comment by emanuil-tolev** [comment]
> Documentation page title should also say “Wellcome compliance tool” not “Cottage Labs”

@markmacgillivray how would I go about changing the `<title>` tag on this page? The individual pages seem to only be able to supply a body in the framework of the new static cl site - how did you change the title of the main page of https://wellcome.test.cottagelabs.com/ to "Wellcome compliance tool" rather than "Cottage Labs"?

**Comment by emanuil-tolev** [comment]
> Various docs page text changes listed on page 11 and 12 of the Wellcome feedback doc (not pasting link since it's edit-by-link sharing).

This is done.

**Comment by markmacgillivray** [comment]
Use js to set it. Look at the document.title setter in the content/index.html

Are you doing these changes or am I?

**Comment by emanuil-tolev** [comment]
> Are you doing these changes or am I?

I had to do the various documentation fixes myself anyway. There's two left - see above. Those ones I thought you're probably better suited to do since you'd probably be faster, but if you're busy with the deployment and so on, I'll get into them.

For the `<title>` I was just curious to be honest.

**Comment by markmacgillivray** [comment]
OK I have made these changes, and the server is ready to serve compliance.cottagelabs.com. Perhaps a quick chat, then you can repoint the domain when suits @emanuil-tolev

**Comment by emanuil-tolev** [comment]
Sure - around any time tomorrow when suits to talk. Just write me on hangouts.

EDIT: Well, probably best after 9am :).

**Comment by emanuil-tolev** [comment]
Well, probably best after 9am :).

**Comment by emanuil-tolev** [comment]
> Text input would ideally be a tad taller so as to not cut off the "Browse" button. I've no idea why this is an issue - presumably bootstrap should have taken care of this, so there must be either an override or simply an unintended clash of styles.

This is still a (smaller now) issue in the offending browser, Firefox. v.46 (just one behind official stable) below:

![image](https://cloud.githubusercontent.com/assets/1190172/16464306/7aa097aa-3e31-11e6-9c80-4c29f4f94aab.png)

No idea why the button padding is so huge. Maybe just a per-browser default? Worth setting button padding to X (3-5) px explicitly?
