### ISSUE TITLE
Reduce caching for Wellcome users

### ISSUE THREAD

**Issue by emanuil-tolev** [CottageLabs/LanternPM#66]
Hi (mostly @markmacgillivray )

Very sorry I missed raising this earlier (Thu last week, specifically..). The live deployment can go ahead as the app stands now, with its current caching, but we still need to discuss this issue in parallel.

Currently results are cached for 7 days.
Wellcome sometimes detects failure to comply with their policy by using the compliance tool (duh). They then advise the organisation that's breaching the policy to correct the article's metadata, licence or whatever is wrong with it in whatever third-party system (e.g. EPMC) it is wrong in.

After that they usually receive a response saying the problem has been corrected. At this point they rerun the original sheet, or a subset with just the problematic article(s) from the sheet. They would like the changes in third party systems (publisher websites, EPMC, etc.) to be reflected in the compliance tool results within 1 day. They did request that we shorten caching to 1-2 days during the development of the new system, but we have ended up with 7 days. This wasn't a problem on test due to its function (jobs being wiped) but it will be a significant sticking point (the last one...) now.

They've never unreasonably rerun sheets or uploaded sheets with an excessive amount of identifiers so from a technical perspective I think we can definitely consider it. What do you think?

**Comment by markmacgillivray** [comment]
Reduced to 1. Just pushing to live now.
