### ISSUE TITLE
https redirects drop path segment

### ISSUE THREAD

**Issue by richard-jones** [CottageLabs/LanternPM#69]
If you type "lantern.cottagelabs.com/terms" into your browser, it will take you to https://lantern.cottagelabs.com

There is some kind of redirect going on which gets rid of the remainder of the path

**Comment by richard-jones** [comment]
Note, this is not just the /terms route - I've seen this problem on several pages, so I presume it is true of the entire CL site.

**Comment by markmacgillivray** [comment]
Oops. Easy fix, will do when back next week.

Mark
