### ISSUE TITLE
Huge papers cause problems

### ISSUE THREAD

**Issue by markmacgillivray** [CottageLabs/LanternPM#82]
http://www.tandfonline.com/doi/full/10.1080/15548627.2015.1100356

**Comment by markmacgillivray** [comment]
The licence check running on this has to do massive amounts of regexing

**Comment by markmacgillivray** [comment]
That is a webpage that is about 37MB in size. Trying to regex check on it locks the machine for a long time. Resetting processes leaves the previous machine stuck processing it, and allocates it onto another machine too. Enough resets and all machines are stuck trying to run 234 regexes over 37MB of text :(

**Comment by markmacgillivray** [comment]
Adding a catch to academic licence to not run if the content size is greater than 10m bytes for the time being.

**Comment by richard-jones** [comment]
Can we add something to the provenance record for such items, explaining
what's happened, so the user knows to check manually?

**Comment by markmacgillivray** [comment]
Done in dev. To push to live soon.
