### ISSUE TITLE
External test harness

### ISSUE THREAD

**Issue by emanuil-tolev** [CottageLabs/LanternPM#84]
- Runs once a day.
- Can be triggered via a GET req.
- Tests accounts system related to Lantern.
  - an admin account will be given to the test harness
  - the test harness has to test creating accounts, using them to submit jobs and removing the accounts
- Tests that when we send certain data to the Lantern API, we get back what we expect
- Test academic licence endpoint

@richard-jones - fill out above with more detail if you have it

**Comment by markmacgillivray** [comment]
Closing this, API now has ongoing development of internal self-testing
