### ISSUE TITLE
Record job type (wellcome/lantern) on submission and use this for completion email and results formatting

### ISSUE THREAD

**Issue by emanuil-tolev** [CottageLabs/LanternPM#85]
When submitting from compliance.cottagelabs.com:
- submission email points to wellcome UI
- completion email points to wellcome UI
- results formatting is wellcome
- no quota is applied

**Comment by emanuil-tolev** [comment]
Wellcome report a problem with the following timeline:
1. no lantern account - can upload spreadsheets OK to compliance.cottagelabs.com
2. lantern account created
3. can no longer upload large sheets to either Wellcome or Lantern, with the following screenshot attached:
   
   ![image](https://cloud.githubusercontent.com/assets/1190172/17405729/90fc36ba-5a58-11e6-8636-37606f661fee.png)
   
   ![image](https://cloud.githubusercontent.com/assets/1190172/17405805/e78efdbe-5a58-11e6-8df7-fe75cfe8d59a.png)

It appears a quota is still being applied.

**Comment by emanuil-tolev** [comment]
Unless we fix this first, we probably need to delete Wellcome's Lantern account before we ask them to check for any other issues, since now they can no longer upload their sheets using their usual account.

**Comment by markmacgillivray** [comment]
I have altered this and checked again. I can definitely now go to compliance UI and submit a job even if there is a lantern account with the same email address, and I get emails that link back to the expected job, and via the compliance UI. 

If there is a lantern account with the same email address, the quota on that account WILL increment with jobs submitted to the compliance UI, but if jobs are submitted via the compliance UI it accepts them even if the matching account is over the max allowed for that account. But if you tried the same account via the lantern UI, it will not accept jobs if the account is over quota.

So they should be able to submit as much as they want via compliance UI, but not on lantern.

**Comment by emanuil-tolev** [comment]
Cecy confirmed this works!
