### ISSUE TITLE
Publicly accessible account page

### ISSUE THREAD

**Issue by richard-jones** [CottageLabs/LanternPM#90]
In order to enable the Monitor tools to integrate with Lantern, we'll need people to be able to give us their API key, so they need a way to get at that.

**Comment by markmacgillivray** [comment]
Lantern is not an overly complex UI. Thinking about making an account page, it occurred that I could put quota and jobs info on that page, and we did already have an issue (not in this milestone) to improve the jobs list. But then that would only leave the new job / job progress info on the main page. So, perhaps it is best to keep it a simple one-pager. In that case, there will not be an "account page", but I will add the extra info required to support Monitor (and other users / usage) onto the main UI page, which is already customised based on the user that is signed in anyway. I believe, for now, this just means adding the user API key somewhere. So I will make some nice improvements to the main UI page, including showing the signed in username / email address and their API key.

**Comment by richard-jones** [comment]
I'm fine with a single-pager, the important thing for this issue is just that the information is close to the user.

**Comment by markmacgillivray** [comment]
This is done in latest version in that the auth actually works and the API key is shown and a logout button is shown. I have also added date and time to the job lists to help differentiate them. However the page could still do with an actual redesign, but there is not time right now to make it look any better. Can come back to it as a design issue. Can close this issue or keep open as reminder for that.

**Comment by richard-jones** [comment]
Functionally this is fine, I think.  I'll reassign this to me to think about the page-flow and the design.

**Comment by richard-jones** [comment]
supserseded by new site design
