### ISSUE TITLE
No completion email received for one sheet

### ISSUE THREAD

**Issue by emanuil-tolev** [CottageLabs/LanternPM#98]
Wellcome report not receiving a completion email for https://compliance.cottagelabs.com/#BbhjstRnDqYbPcRtW .

I am putting it in the Wellcome milestone as it was listed as a requirement for considering the service stable enough, but this might be difficult to debug. As we're using mailgun, we could check in there.

I have so far received numerous submission and completion emails from the live system without much delay or failure so I can't confirm exactly why this has happened.

If you've got a clear idea of what could be the problem @markmacgillivray , then feel free to fix whatever it is. In the meantime I'm going to assign this to myself, to try to get the mailgun log for this specific email and see if I can/can't confirm that the system at least tried to send it.

**Comment by markmacgillivray** [comment]
It is possible it was just due to downtime, if it coincided with a pull of new code or something like that. If it just one, and over the last few days I have done dozens that all worked fine, perhaps we just close this and investigate if evidence of a systemic problem arises @emanuil-tolev

**Comment by emanuil-tolev** [comment]
Yeah, I also want to do that. Hopefully just won't happen again once the 2 weeks after our final fixes start..

**Comment by emanuil-tolev** [comment]
Reopening this just to remind me I need to respond to it as a line item - but there's still no action to take on this at the moment.

**Comment by emanuil-tolev** [comment]
Hmm, I am running the app locally (master branch) and it sends me emails just fine. But then I see this:

```
W20160811-15:36:10.292(1)? (STDERR) 
W20160811-15:36:10.293(1)? (STDERR) Error: Greeting never received
W20160811-15:36:10.293(1)? (STDERR)     at SMTPClient.<anonymous> (/home/emanuil/.meteor/packages/email/.1.0.12.1bctc66++os+web.browser+web.cordova/npm/node_modules/simplesmtp/lib/client.js:268:25)
W20160811-15:36:10.293(1)? (STDERR)     at Timer.listOnTimeout [as ontimeout] (timers.js:121:15)
=> Exited with code: 8
```

Probably needs a guard of some kind to .. well, retry the email a few times? Could also display a message to the user that we couldn't send them an email, if we were to get really clever.

This error happened on (as far as I can see) trying to send the ~~completion~~ submission email.

**Comment by emanuil-tolev** [comment]
Sorry, error probably related to *submission* email, not completion. I have 2 submission and 3 completion emails in my inbox.

**Comment by emanuil-tolev** [comment]
Removing from Wellcome milestone. If the occasional lost email is not that important then we should leave adding retry code for later. Tthey do appear to be very rare e.g. I've only seen the one with the error above.

**Comment by richard-jones** [comment]
closing, will re-open if something similar happens again
